# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ASUS\programming\qt_programs\masnou\details.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore,QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 561)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.details_rounds_table = QtWidgets.QTableView(Form)
        self.details_rounds_table.setObjectName("details_rounds_table")
        self.verticalLayout.addWidget(self.details_rounds_table)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 60))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Detalles de ronda "))
