# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ASUS\programming\qt_programs\masnou\updatedlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(994, 717)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.spots_container = QtWidgets.QFrame(Form)
        self.spots_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.spots_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.spots_container.setObjectName("spots_container")
        self.verticalLayout.addWidget(self.spots_container)
        self.checks_container = QtWidgets.QGroupBox(Form)
        self.checks_container.setMinimumSize(QtCore.QSize(0, 80))
        self.checks_container.setObjectName("checks_container")
        self.verticalLayout.addWidget(self.checks_container)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.accept_btn = QtWidgets.QPushButton(self.frame_3)
        self.accept_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.accept_btn.setObjectName("accept_btn")
        self.horizontalLayout.addWidget(self.accept_btn)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checks_container.setTitle(_translate("Form", "Seleccione el ganador"))
        self.accept_btn.setText(_translate("Form", "Aceptar"))
        self.pushButton_2.setText(_translate("Form", "Cancelar"))
